# Generated by Django 5.2.4 on 2025-07-31 01:21

import django.db.models.deletion
import django_ckeditor_5.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Section",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=64, unique=True)),
                ("slug", models.SlugField(unique=True)),
                (
                    "authors",
                    models.ManyToManyField(
                        blank=True, related_name="sections", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=250)),
                ("slug", models.SlugField(unique=True)),
                (
                    "hero_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="articles/hero/"
                    ),
                ),
                ("body", django_ckeditor_5.fields.CKEditor5Field(verbose_name="Text")),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "Draft"), ("pub", "Published")],
                        default="draft",
                        max_length=5,
                    ),
                ),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "authors",
                    models.ManyToManyField(
                        related_name="articles", to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="articles",
                        to="articles.section",
                    ),
                ),
            ],
            options={
                "ordering": ("-published_at",),
            },
        ),
    ]
